update install

diff --git a/install b/install
--- a/install
+++ b/install
@@ -11,10 +11,16 @@ cd ..
 echo "Cloning XiaoMiToolV2..."
 git clone https://github.com/francescotescari/XiaoMiToolV2 -b linux || echo "Failed to clone XiaoMiTool!";exit 1
 cd XiaoMiToolV2
+if [ `uname -m` == i386 ] || [ `uname -m` == i686 ]; then
+for i in {adb,fastboot}; do
+echo copying $i for i386...
+cp $(which $i) ./res/tools/$i || echo 'Failed to copy $i !' && exit 1
+done
+fi
 echo "Building XiaoMi Tool..."
 case `uname -m` in
- armv7l|armv7) JAVA_HOME=/usr/lib/jvm/java-11-openjdk-armhf ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
- aarch64) JAVA_HOME=/usr/lib/jvm/java-11-openjdk-arm64 ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
+ i386|i686) JAVA_HOME=/usr/lib/jvm/java-11-openjdk-i386 ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
+ amd64|x86_64) JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 ./gradlew build || echo "Failed to build XiaoMiToolV2!" && exit 1 ;;
  *) echo "Failed to detect OS CPU architecture! Something is very wrong." && exit 1 ;;
 esac
 cd $cur
